#!/usr/bin/env bash

declare METADATADIR="../v0/developer"

jq \
  --arg region "${1:?Specify a region e.g. eu10}" \
  --from-file services-in-region.jq \
  --raw-output \
  --slurp \
  $METADATADIR/*.json
