name: Update Metadata Files
# Update the metadata information

on:
  workflow_dispatch: {}

env:
  METADATA_SOURCE_REPO: btp-metadata-fetcher
  METADATA_SOURCE_OWNER: btp-setup-automator
  
jobs:
  fetch-metadata:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"

      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Prepare collection of data from metadata repository"
        run: |
          cd .github/scripts
          npm ci
      - name: "Execute collection of data from metadata repository"
        run: |
          cd .github/scripts
          export GITHUB_ENTERPRISE_TOKEN=${{ secrets.GITHUB_ENTERPRISE_TOKEN }} 
          export GITHUB_ENTERPRISE_API_URL=${{ secrets.GITHUB_ENTERPRISE_API_URL }}
          export METADATA_SOURCE_VERSION = ${{ secrets.METADATA_SOURCE_VERSION }}
          export METADATA_SOURCE_DIR = ${{ secrets.METADATA_SOURCE_DIR }}}} 
          export METADATA_SOURCE_REPO=${{ env.METADATA_SOURCE_REPO }}
          export METADATA_SOURCE_OWNER=${{ env.METADATA_SOURCE_OWNER }}
          npm run fetch:metadata
      - name: "Store changes in GH repository"
        run: |
          git add -A
          git config user.email "btprepobot@users.noreply.github.com"
          git config user.name "BTP Metadata Repo Bot"
          git diff --quiet && git diff --staged --quiet || git commit -m "[btpmr-bot] $(date '+%Y-%m-%d %H:%M:%S'): fetched BTP metadata"
          git push origin ${{ github.ref_name }}
